### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by mrdoob** [react-spring/cannon-es#36] opened 2020-06-23 06:18 UTC
We are considering using `cannon-es` in three.js but seems like there's a performance regression.

@Mugen87 converted cannon.js to modules and here's the running example:
https://raw.githack.com/mrdoob/three.js/dev/examples/physics_cannon_instancing.html

<img width="1127" alt="Screen Shot 2020-06-22 at 11 14 43 PM" src="https://user-images.githubusercontent.com/97088/85367616-8e7af000-b564-11ea-8864-75bdf59c48f5.png">

This is the same example using `cannon-es`:
https://raw.githack.com/Mugen87/three.js/dev45/examples/physics_cannon_instancing.html

<img width="1126" alt="Screen Shot 2020-06-22 at 11 12 39 PM" src="https://user-images.githubusercontent.com/97088/85367606-8a4ed280-b564-11ea-8d22-f461e65ff150.png">

https://github.com/mrdoob/three.js/pull/19709

**Comment by marcofugaro** [comment] 2020-06-23 07:51
Thanks for the issue and the usage example. 
This also looks related to #16. I'll look into it soon!

**Comment by codynova** [comment] 2020-06-23 08:13
I only had a moment to look at this as I'm headed to bed but I definitely agree it looks related to #16 and #18

**Comment by codynova** [comment] 2020-06-23 08:14
Mugen's cannon-es code is [here](https://github.com/Mugen87/three.js/blob/dev45/examples/physics_cannon_instancing.html) and the original cannon.js version [here](https://github.com/mrdoob/three.js/blob/dev/examples/physics_cannon_instancing.html)

**Comment by arpu** [comment] 2020-06-23 13:22
maybe i am wrong here but the last para should be not the frameRate
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/physics/CannonPhysics.js#L193

more a value of 10 for maxSubSteps

**Comment by marcofugaro** [comment] 2020-06-27 11:22
Hello friends, I've discovered the issue.

Basically there are tons or commit which are in the cannon.js repo but haven't been published to npm or built into the bundle. [Here is the full list](https://github.com/schteppe/cannon.js/compare/v0.6.2...master).
When we built the source files again in cannon-es, we inherited automatically all those commits.

Between these commits there is [86b0444](https://github.com/schteppe/cannon.js/commit/86b0444c93356aeaa25dd1af795fa162574c6f4b), where schteppe implemented the fixed timestepping from the [last snippet of this famouse article](https://gafferongames.com/post/fix_your_timestep/), however it was left unfinished or was not tested properly, leading to the framerate issues.

I've tried to fix those issues in #40, if you guys @mrdoob and @Mugen87 could test with the cannon-es bundle from that branch that would be grand 🙏 

Also @codynova issue #16 should be fixed as well, could you do a test? 🙏 

@arpu is right, the third parameter is used to tell how many maximum internal steps the `step()` function can take if there is too much lag. If you set it to 1, it doesn't take any internal steps, but the simulation is technically slower. If you set it to an high number, it takes as many steps as needed to make the interaction have a fixed timestep, however if the step is expensive (a lot of boxes), taking too many steps can cause lag by itself.

**Comment by Mugen87** [comment] 2020-06-27 11:55
@marcofugaro The performance seems better with your changes. However I have more than 400 cubes in the scene, the performance gets drops significantly to an unusable framerate. This does not happen with the original `cannon.js` version.

**Comment by marcofugaro** [comment] 2020-06-27 12:38
@Mugen87 Oddly enough, that's a feature.
Please read the description of #40, it's the whole idea behind [this article]()

If you want the behaviour of the previous cannon.js, you can call `world.step(frameTime)` without any other arguments. The simulation with 400 boxes will run "in slow motion" but at a stable framerate.

However now that you mention it, it makes sense to have the threshold at at least 30fps, not 10.

**Comment by marcofugaro** [comment] 2020-07-03 16:38
@Mugen87 do you have time to test again? 🙏 
It shouldn't go below 30fps, rather it will slow down a bit.

**Comment by Mugen87** [comment] 2020-07-04 09:01
Performance seems better now. Mostly around 25-27 FPS when having 400 cubes in `physics_cannon_instancing`.

However, the performance of `cannon-es` is still worse than the original `cannon.js`. With the same settings (400 cubes in `physics_cannon_instancing`) I get almost around 52 FPS.

**Comment by marcofugaro** [comment] 2020-07-04 11:08
Alright, that is working as intended! 🎉

The simulation now has more time to catch up than before, this works in favor of people using cannon.js in a web worker.

Users can still get the previous `cannon.js` behaviour (~60fps) by passing 1 to the third argument of the `step()` function (suggested when there are a lot of bodies to simulate).

```js
world.step(frameTime, delta, 1)
```

Thanks for testing again!

**Comment by Mugen87** [comment] 2020-07-04 13:29
So `THREE.CannonPhysics` needs an change in the following place to restore the "old" behavior?

https://github.com/mrdoob/three.js/blob/3ca144cac1c81ada7496e2f4790877848c6b4aa9/examples/jsm/physics/CannonPhysics.js#L193

**Comment by marcofugaro** [comment] 2020-07-04 17:55
Yup, currently in that line, the third parameter `frameRate` is wrong, as it's not related to the framerate at all.

It should be called 'maxSubSteps` and should be set to a value of 1 or a really small integer in your case.
It was like this also in the original cannon.js.

**Closed** 2020-07-06 18:57 UTC

**Comment by codynova** [comment] 2020-07-06 20:24
A new version of cannon-es has been released with Marco's fixes for variable framerate simulation `cannon-es@0.15.0`
